package com.ken.rynoa.dao;

import com.ken.rynoa.model.RyUser;
import com.ken.rynoa.model.RyUserExample;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface RyUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int countByExample(RyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int deleteByExample(RyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int insert(RyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    boolean insertSelective(RyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    List<RyUser> selectByExample(RyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    RyUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RyUser record, @Param("example") RyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RyUser record, @Param("example") RyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ry_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RyUser record);

    RyUser userLogin(@Param("username") String username, @Param("password")String password);
}