package com.ken.rynoa.model;

import java.util.Date;

public class RyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_user.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_user.loginRole
     *
     * @mbggenerated
     */
    private String loginrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry_user.createTime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_user.uid
     *
     * @return the value of ry_user.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_user.uid
     *
     * @param uid the value for ry_user.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_user.username
     *
     * @return the value of ry_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_user.username
     *
     * @param username the value for ry_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_user.password
     *
     * @return the value of ry_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_user.password
     *
     * @param password the value for ry_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_user.email
     *
     * @return the value of ry_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_user.email
     *
     * @param email the value for ry_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_user.loginRole
     *
     * @return the value of ry_user.loginRole
     *
     * @mbggenerated
     */
    public String getLoginrole() {
        return loginrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_user.loginRole
     *
     * @param loginrole the value for ry_user.loginRole
     *
     * @mbggenerated
     */
    public void setLoginrole(String loginrole) {
        this.loginrole = loginrole == null ? null : loginrole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry_user.createTime
     *
     * @return the value of ry_user.createTime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry_user.createTime
     *
     * @param createtime the value for ry_user.createTime
     *
     * @mbggenerated
     */
    public String setCreatetime(String createtime) {
        return this.createtime = createtime;
    }
}